### ISSUE TITLE
AttributeError: attribute '__doc__' of 'instancemethod' objects is not writable

### ISSUE THREAD

**Issue by dorkerdevil** [Imtiazkarimik23/ATFuzzer#2]
i did sudo pip install -r requirements.txt 
and successfully installed every required module 
then, i ran sudo ./executFuzzer.py multi <adb device id>

and got this error

AttributeError: attribute '__doc__' of 'instancemethod' objects is not writable

**Comment by FabrizioCicala** [comment]
the issue might be related to the latest version of pybluez (0.23), try to install the version 0.22 with the command 'pip install PyBluez==0.22'

**Comment by dorkerdevil** [comment]
resolved !!

**Comment by FabrizioCicala** [comment]
Great! I also updated the requirements.txt file. Thank you for the notification!
